// Complete JourneyBook Questions Database
const JOURNEYBOOK_QUESTIONS = {
    values: {
        TRAIT: [
            { question: "Your age is UNDER", options: ["30", "40", "50", "60"], image: "../../JOURNEYBOOK/Values/age.jpg" },
            { question: "Your age is OVER", options: ["30", "40", "50", "60"], image: "../../JOURNEYBOOK/Values/age.jpg" },
            { question: "Your GENDER IS", options: ["MALE", "FEMALE", "GROUP"], image: "../../JOURNEYBOOK/Values/groupphoto01.jpg" },
            { question: "Date of Birth - Used for Astrology - Information not shown", options: [], image: "../../JOURNEYBOOK/Values/TreasureMap.jpg" },
            { question: "Time of Birth - Used for Astrology - Information not shown", options: [], image: "../../JOURNEYBOOK/Values/TreasureMap.jpg" },
            { question: "City of Birth - Used for Astrology - Information not shown", options: [], image: "../../JOURNEYBOOK/Values/Globe.png" },
            { question: "Country of Birth - Used for Astrology - Information not shown", options: [], image: "../../JOURNEYBOOK/Values/Globe.png" },
            { question: "State of Birth - Used for Astrology - Information not shown", options: [], image: "../../JOURNEYBOOK/Values/Globe.png" },
            { question: "What is your height?", options: [], image: "../../JOURNEYBOOK/Values/body-types.jpg" },
            { question: "What is your weight?", options: [], image: "../../JOURNEYBOOK/Values/take-care-of-your-body.jpg" },
            { question: "What are you looking for?", options: ["MALE", "FEMALE", "GROUP"], image: "../../JOURNEYBOOK/Values/groupphoto01.jpg" },
            { question: "COMFORTABLE WITH…", options: ["Marriage", "Long Term Relationship", "Something Short and Sweet", "Casual Sex", "An Affair", "A Frienship", "Friends with Benefits", "Go on an Outing", "Chat", "PenPal"], image: "../../JOURNEYBOOK/Values/690x380-Romance-Kissing.jpg" },
            { question: "WOULD LIKE…", options: ["Marriage", "Long Term Relationship", "Something Short and Sweet", "Casual Sex", "An Affair", "A Frienship", "Friends with Benefits", "Go on an Outing", "Chat", "PenPal"], image: "../../JOURNEYBOOK/Values/heart-throb.png" },
            { question: "MIGHT ALSO LIKE…", options: ["Marriage", "Long Term Relationship", "Something Short and Sweet", "Casual Sex", "An Affair", "A Frienship", "Friends with Benefits", "Go on an Outing", "Chat", "PenPal"], image: "../../JOURNEYBOOK/Values/monogamy.jpg" },
            { question: "IT WOULD BE GREAT…", options: ["Marriage", "Long Term Relationship", "Something Short and Sweet", "Casual Sex", "An Affair", "A Frienship", "Friends with Benefits", "Go on an Outing", "Chat", "PenPal"], image: "../../JOURNEYBOOK/Values/old_couple.jpg" },
            { question: "MUST HAVE…", options: ["Marriage", "Long Term Relationship", "Something Short and Sweet", "Casual Sex", "An Affair", "A Frienship", "Friends with Benefits", "Go on an Outing", "Chat", "PenPal"], image: "../../JOURNEYBOOK/Values/monogamy2.jpg" },
            { question: "IDEAL AGE GROUP OF YOUR PARTNER..", options: ["30", "40", "50", "60"], image: "../../JOURNEYBOOK/Values/age.jpg" }
        ],
        Core: [
            { question: "Is Race Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/race.jpg" },
            { question: "Is Ethnicity Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/race.jpg" },
            { question: "Is Age Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/age.jpg" },
            { question: "Is Religion Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Is Marriage Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/monogamy.jpg" },
            { question: "Is a Long Term Relationship Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/old_couple.jpg" },
            { question: "Is Monogamy Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/monogamy2.jpg" },
            { question: "Are Looks Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/looks_important.jpg" },
            { question: "Do you want Children?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/Group-children-01.jpg" },
            { question: "Is Income Important?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Values/income.jpg" }
        ],
        Religion: [
            { question: "Agnosticism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Atheism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Buddhism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Catholism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Christiantiy", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Druidism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "FengShui", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Hinduism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Islam", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Judaism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Kabbalah", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Mormonism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Neo_Paganism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Reiki", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Scientology", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Taoism", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" },
            { question: "Wicca", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/agnosticism.jpg" }
        ],
        Personality: [
            { question: "Are you an Outdoor Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/Outdoor_Person.png" },
            { question: "Are you a Country Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/country.jpg" },
            { question: "Are you a City Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/City_Person.jpg" },
            { question: "Are you an Exercize Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/exercise.jpg" },
            { question: "Are you an an Animal Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/animal_people1.jpg" },
            { question: "Are you a Dog Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/Dog_Person.png" },
            { question: "Are you a Cat Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/cat-person.jpg" },
            { question: "Do you like other kinds of Animals?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/other_animals.jpg" },
            { question: "Are you a Romantic Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/690x380-Romance-Kissing.jpg" },
            { question: "Are you a Stioic Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/stoic_person.jpg" },
            { question: "Are you a Serious Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/06-serious.jpg" },
            { question: "Are you a Hard Working Person?", options: ["YES", "NO", "KIND OF", "NOT AT ALL", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Values/hardworking.jpg" }
        ]
    },
    compatibility: {
        Intellect: [
            { question: "Alchemy", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/alchemy.png" },
            { question: "Archaeology", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/archeology.png" },
            { question: "Astronomy", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/Astronomy.jpg" },
            { question: "Biology", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/biology.png" },
            { question: "Blogging", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/blogging.png" },
            { question: "Chemistry", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/chemistry.png" },
            { question: "History", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/history.png" }
        ],
        Adventure: [
            { question: "AmusementParks", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/amusement_parks.jpg" },
            { question: "AntiqueShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/antiques03.jpg" },
            { question: "ArtGalleries", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/galerie-de-arta.jpg" },
            { question: "BeachCombing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/beachcombing.jpg" },
            { question: "BirdWatching", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/birdwatching.jpg" },
            { question: "Clubbing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/clubbing.jpg" },
            { question: "CoffeeShops", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/at a cafe.jpg" },
            { question: "FineDining", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/firefly-restaurant-casual-fine-dining-panama--L-dYW9pR.jpeg" },
            { question: "Fishing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/fishing.jpg" },
            { question: "FleaMarkets", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/flea market.jpg" },
            { question: "Gambling", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/gambling-spells.jpg" },
            { question: "GarageSales", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/yard_sale_northern_ca_2005.jpg" },
            { question: "Movies", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/movie goers.jpg" },
            { question: "Museums", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/museums.jpg" },
            { question: "MusicalTheater", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/musicaltheaters.jpg" },
            { question: "Opera", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/opera-audiences.jpg" },
            { question: "Raves", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/raves.jpg" },
            { question: "RenaissanceFaires", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/renaissance-faire.jpg" },
            { question: "Shopping", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/shopping.jpg" },
            { question: "Travel", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/Couples-Volunteering.jpg" },
            { question: "Volenteerism", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/Couples-Volunteering.jpg" }
        ],
        Hobbies: [
            { question: "Beading", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/beading.png" },
            { question: "BodyArt", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/body art.png" },
            { question: "CandleMaking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/candlemaking.png" },
            { question: "Cooking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/cooking.png" },
            { question: "CrossStitching", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/crossstitch.png" },
            { question: "Drawing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/drawing.png" },
            { question: "Gardening", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/gardening.png" },
            { question: "Herbalism", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/herbalism.png" },
            { question: "Investing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/investing.png" },
            { question: "Karaoke", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/kareoke.png" },
            { question: "Knitting", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/knitting.png" },
            { question: "Meditation", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/meditation.png" },
            { question: "Painting", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/painting.png" },
            { question: "Photography", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/photography.png" },
            { question: "Pottery", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/pottery.png" },
            { question: "Sculpting", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/sculpyimg.png" },
            { question: "Sewing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/sewing.png" },
            { question: "Singing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/singing.png" },
            { question: "SoapMaking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/soap making.png" },
            { question: "Tattoos", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/tattoo.png" },
            { question: "ModelMaking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/modelmaking.png" },
            { question: "JewelryMaking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/jewelrymaking.png" },
            { question: "MakingMusic", options: ["Guru", "Expert", "Advanced", "Intermediate", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/makingmusic.png" }
        ],
        Diversions: [
            { question: "ArcadeGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/Arcade Games.jpg" },
            { question: "BoardGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/cards.png" },
            { question: "CardGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/cards.png" },
            { question: "Cartoons", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/cartoons.png" },
            { question: "Chess", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/chess.png" },
            { question: "ComedyShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/comedy.png" },
            { question: "CookingShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/cooking2.png" },
            { question: "DanceTVShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/dancetv.png" },
            { question: "DramaTVShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/dramatv.png" },
            { question: "HistoryShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/historyshows.png" },
            { question: "HorrorMovies", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/horror.png" },
            { question: "MMORPGs", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/mmorpgs.png" },
            { question: "MurderMysteries", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/murder-mystery-man.png" },
            { question: "Newspapers", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/newspapers.png" },
            { question: "OnlineRPGs", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/RPG.png" },
            { question: "PuzzleGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/puzzle.png" },
            { question: "RealityTV", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/realitytv.png" },
            { question: "RolePlayingGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/roleplay.png" },
            { question: "RomanceNovels", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/romancenovels.png" },
            { question: "SciFi", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/scifi.png" },
            { question: "SimulationGames", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/simgames.png" },
            { question: "Sitcoms", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sitcom.png" },
            { question: "SoapOperas", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/soapopera.png" },
            { question: "TalentShows", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/gottalent.png" },
            { question: "TrueCrime", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/truecrime.png" },
            { question: "Thrillers", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/thriller.png" },
            { question: "TVNews", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/tvnews.png" },
            { question: "TVSports", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/tvsports.png" }
        ],
        Music: [
            { question: "Alternative", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Americana", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "BlueGrass", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Blues", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Classical", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Country", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Eighties", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Electronica", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "EMO", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Folk", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Funk", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "HeavyMetal", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "HipHop", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Industrial", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Jazz", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "NewAge", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "NewWave", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Nineties", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Oldies", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Opera", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Operetta", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Pop", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Punk", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "RNB", options: ["No Opinion", "Love it", "Like it", "Curious about", "Tolerate it", "Dislike it", "Hate it", "Hard Limit"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Rap", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Reggae", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Rock", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Seventies", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Soca", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Salsa", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Cuban50s", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "BigBand", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Banghra", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Gospel", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "BoysChoir", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" },
            { question: "Bollywood", options: ["No Opinion", "Love it", "Like it", "Curious about", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/music.png" }
        ],
        Athletics: [
            { question: "Aerobics", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Bicyling", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Camping", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Climbing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Dancing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Gymnastics", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Hiking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "HorsebackRiding", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Hunting", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "MartialArts", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Pilates", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Rafting", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "RollerBlading", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Running", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Sailing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "ScubaDiving", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "SkateBoarding", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Snorkeling", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Surfing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Tai_Chi", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "UltimateFrisbee", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Walking", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "WeightTraining", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "WindSurfing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" },
            { question: "Yoga", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/athletics.png" }
        ],
        Sports: [
            { question: "AutoRacing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Badminton", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Baseball", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Basketball", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "BMX", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "BodyBuilding", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Bowling", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Boxing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Darts", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Football", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Golf", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "HorseRacing", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "IceHockey", options: ["Guru", "Expert", "Advanced", "Intermediate", "Beginner", "Want to Try"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "KickBoxing", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "MMA", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "PaintBall", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Skiing", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "SkyDiving", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "SnowBoarding", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Soccer", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "StreetHockey", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Swimming", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Tennis", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Volleyball", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" },
            { question: "Wrestling", options: ["Guru", "Expert", "Advanced", "Intermediate"], image: "../../JOURNEYBOOK/Compatibility/sports.png" }
        ]
    },
    intimacy: {
        Basic: [
            { question: "Is Quantity as Important as Quality", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (1).jpg" },
            { question: "How many times a week would like to have sex?", options: [], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (2).jpg" },
            { question: "Are you tame?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (3).jpg" },
            { question: "Are yo wild?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (4).jpg" },
            { question: "Are you Extreme?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (5).jpg" },
            { question: "Are you open minded?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (6).jpg" },
            { question: "Do you like experimentation?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (7).jpg" },
            { question: "Are you kinky?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (8).jpg" },
            { question: "Are you perverse?", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (9).jpg" },
            { question: "Do you like to role play? Or are you a…", options: ["Dominant", "Domme", "Switch", "submissive"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (10).jpg" }
        ],
        "Looking For": [
            { question: "A long term sexually relationship", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (11).jpg" },
            { question: "A relationship that is also sexually charged", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (12).jpg" },
            { question: "A Mentor/Teacher", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (13).jpg" },
            { question: "Just to play", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (14).jpg" },
            { question: "A Princess/Slut", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (15).jpg" },
            { question: "Kinky friends", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (16).jpg" },
            { question: "A Master", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (17).jpg" },
            { question: "Kinky or playtime Events", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (18).jpg" },
            { question: "A Domestic Slave", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (19).jpg" },
            { question: "A Dominant", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (20).jpg" },
            { question: "A Domme", options: ["YES", "NO", "MAYBE"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (21).jpg" },
            { question: "A sub", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (22).jpg" },
            { question: "A Sex Slave", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (23).jpg" },
            { question: "A Switch Woman", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (24).jpg" },
            { question: "A Switch Male", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (25).jpg" },
            { question: "A Dom Trans", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (26).jpg" },
            { question: "A sub trans", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (27).jpg" },
            { question: "A Dom Domme Couple", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (28).jpg" },
            { question: "A sub sub couple", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (29).jpg" },
            { question: "A Fem Domme Couple", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (30).jpg" },
            { question: "A Male Dom Couple", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (31).jpg" },
            { question: "Online Cyber Play", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (32).jpg" },
            { question: "A poly house", options: ["YES", "NO", "MAYBE", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (33).jpg" }
        ],
        "Kinky Play (Warning)": [
            { question: "Do you like Ass Play?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (34).jpg" },
            { question: "Do you like Begging?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (35).jpg" },
            { question: "Do you like Blindfolds?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (36).jpg" },
            { question: "Do you like Bodyworship?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (37).jpg" },
            { question: "Do you like Bondage?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (38).jpg" },
            { question: "Do you like Breast Play?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (39).jpg" },
            { question: "Do you like Cages?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (40).jpg" },
            { question: "Do you like Crops?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (41).jpg" },
            { question: "Do you like Canes?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (42).jpg" },
            { question: "Do you like CBT?", options: ["Anytime / Anyplace", "Want it wherever", "Just in the Bedroom", "Once in a while for Spice", "Curious and Ready", "Just Curious"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (43).jpg" }
        ],
        TRAIT: [
            { question: "Your GENDER ASSOCIATION IS", options: ["Male", "Female", "Transvestite", "Crossdresser", "Trans - M2F", "Trans - F2M", "Queer", "Butch", "Femme"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (80).jpg" },
            { question: "Your SEXUALITY IS", options: ["Straight", "Heteroflexible", "Bisexual", "Homoflexible", "Gay", "Lesbian", "Queer", "Pansexual", "Evolving", "Asexual", "Unsure"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (81).jpg" },
            { question: "What are you looking for?", options: ["Male", "Female", "Transvestite", "Crossdresser", "Trans - M2F", "Trans - F2M", "Queer", "Butch", "Femme"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (82).jpg" },
            { question: "Are you interested in a Partner who IS", options: ["Straight", "Heteroflexible", "Bisexual", "Homoflexible", "Gay", "Lesbian", "Queer", "Pansexual", "Evolving", "Asexual", "Unsure"], image: "../../JOURNEYBOOK/Intimacy/jbimage_xx (1).jpg" }
        ]
    }
};